apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openjdk-demo-ingress
  labels:
    app: openjdk-demo
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: {{ .Values.letsEncrypt.issuer }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/acme-challenge-type: {{ .Values.letsEncrypt.challengeType }}
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "openjdk-demo-service"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: {{ .Values.appgw.rootCertificateName }}
spec:
  tls:
    - hosts:
        - {{ .Values.dnsname }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.dnsname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openjdk-demo-service
                port:
                  name: https