apiVersion: v1
kind: Service
metadata:
  name: openjdk-demo-service
  labels:
    app: openjdk-demo
spec:
  selector:
    app: openjdk-demo
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8080