replicaCount: 1

nameOverride: "openjdk-demo"

dnsname: openjdk-demo.local

appgw:
  rootCertificateName: "openjdk-demo-service"

csisecrets:
  vaultname: ""
  tenantId: ""
  clientId: ""

image:
  repository: gordonbmsft/openjdk-demo
  pullPolicy: Always
  tag: "" #image tag should be set in Chart.yaml - but where it's a strange tag, just override here

service:
  type: ClusterIP
  port: 80

letsEncrypt:
  issuer: "letsencrypt-staging"
  challengeType: "http01"
  secretname: "openjdk-tls"