replicaCount: 1

nameOverride: "openjdk-demo"

dnsname: openjdk-demo.local

appgw:
  rootCertificateName: "openjdk-demo-service" #AppGw is fussy about the CN matching the incoming hostheader, otherwise 502's ensue
  frontendCertificateName: "openjdk-kvssl-fe"
  usePrivateIp: false

csisecrets:
  vaultname: ""
  tenantId: ""
  clientId: ""

image:
  repository: gordonbmsft/openjdk-demo
  pullPolicy: Always
  tag: "" #image tag should be set in Chart.yaml - but where it's a strange tag, just override here
