front:
  replicaCount: 3
  fullnameOverride: "azure-vote-front"
  env:
    redis: "azure-vote-back"
  service:
    type: "" #LoadBalancer
    azureLbInternal: "false"

back:
  replicaCount: 1
  fullnameOverride: "azure-vote-back"

ingress:
  enabled: true
  appGwPrivateIp: false