{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "{{ .Values.ingress.appGwPrivateIp }}"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-azure-vote-front
          servicePort: 80
{{- end }}
