{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "{{ index .Values "azure-vote-front" "service" "azureLbInternal" }}"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
{{- end }}
