name: Package Helm Charts
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enumerate modified charts
        run: |
          echo "TODO"

      - name: Package modified charts
        run: |
          helm package .\azurevote\
